# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Cocoaphony
email: rob@neverwood.org
author: Rob Napier
description: >- # this means to ignore newlines until "baseurl:"
  Mac and iOS development with a focus on Swift and functional programming
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://robnapier.net" # the base hostname & protocol for your site, e.g. http://example.com
twitter_user: cocoaphony
github_user:  rnapier

# Build settings
# markdown: rdiscount
# rdiscount:
#   extensions:
#     - autolink
#     - footnotes
#     - smart

paginate: 10          # Posts per page on the blog index
excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles
excerpt_separator: "<!--more-->"

sidebar: collapse

titlecase: true       # Converts page and post titles to titlecase

root: "/"
permalink: /:title
source: source
destination: docs
plugins: 
  - jekyll-paginate
  - jekyll-feed
plugins_dir: plugins


# highlighter: rogue # default python pygments have been replaced by pygments.rb

subscribe_rss: /atom.xml

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
